apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resource-sample-kustomization
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: Resource
    name: resource-sample-kustomization
  path: "."
  prune: true
  timeout: 1m
