apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  labels:
    app.kubernetes.io/name: ocm-k8s-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: resource-sample-kustomization
spec:
  componentRef:
    name: podinfo-component
  interval: 10m
  resource:
    byReference:
      resource:
        name: mychart-kustomization
