apiVersion: delivery.ocm.software/v1alpha1
kind: ResourceConfig
metadata:
  name: resource-configuration
spec:
  rules:
  - yamlsubst:
      source:
        value: "nginx:latest"
      target:
        file:
          path: values.yaml
          value: image.repository
